export const products = [
  // --- TECH ---
  { id: 1, name: "Pro Noise-Cancelling Earbuds", price: 249.00, category: "Tech", rating: 4.9, reviews: 842, image: "https://images.unsplash.com/your-new-image-link-here?auto=format&fit=crop&w=600&q=80", description: "Studio-quality wireless audio with adaptive active noise cancellation.", features: ["Adaptive ANC", "30-hour battery life", "Bluetooth 5.3", "IPX4 Water resistant"] },
  { id: 2, name: "Smart Home Hub Speaker", price: 79.99, category: "Tech", rating: 4.6, reviews: 328, image: "https://images.unsplash.com/photo-1543512214-318c7553f230?auto=format&fit=crop&w=600&q=80", description: "Voice-controlled smart assistant with rich, room-filling spatial audio.", features: ["Spatial audio", "Voice recognition", "Matter & Thread support", "Hardware privacy switch"] },
  { id: 3, name: "Wireless Mechanical Keyboard", price: 159.99, category: "Tech", rating: 4.9, reviews: 189, image: "https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=600&q=80", description: "Tactile, hot-swappable mechanical keyboard with customizable RGB.", features: ["Hot-swappable switches", "Aircraft-grade aluminum", "Per-key RGB", "Wireless & Wired modes"] },
  { id: 4, name: "Magnetic Power Bank 10K", price: 49.99, category: "Tech", rating: 4.7, reviews: 612, image: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?auto=format&fit=crop&w=600&q=80", description: "Snap-on magnetic portable charger for all-day power on the go.", features: ["MagSafe compatible", "10,000mAh capacity", "20W USB-C PD", "Foldable kickstand"] },
  { id: 5, name: "34\" Ultrawide Curved Monitor", price: 499.00, category: "Tech", rating: 4.8, reviews: 256, image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=600&q=80", description: "Immersive 34-inch curved display for ultimate productivity and gaming.", features: ["3440 x 1440 WQHD", "165Hz refresh rate", "90W USB-C power delivery", "sRGB 99% color gamut"] },
  { id: 6, name: "3-in-1 Wireless Charging Stand", price: 39.99, category: "Tech", rating: 4.5, reviews: 890, image: "https://images.unsplash.com/photo-1622445275463-afa2ab738c34?auto=format&fit=crop&w=600&q=80", description: "Sleek aluminum charging tree for your phone, watch, and earbuds.", features: ["15W fast charging", "Weighted anti-slip base", "Sleep-friendly LED", "Universal Qi compatibility"] },

  // --- ACCESSORIES ---
  { id: 7, name: "Chronograph Analog Watch", price: 145.00, category: "Accessories", rating: 4.8, reviews: 315, image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80", description: "An elegant, lightweight timepiece featuring a premium leather strap and stopwatch.", features: ["Sapphire crystal glass", "Italian leather strap", "Water-resistant 50m", "Precision quartz movement"] },
  { id: 8, name: "Commuter Leather Backpack", price: 110.50, category: "Accessories", rating: 4.9, reviews: 603, image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80", description: "Durable, weather-resistant backpack perfect for daily commutes and travel.", features: ["Fits 16-inch laptops", "Ergonomic padded straps", "Hidden RFID pocket", "Full-grain vegan leather"] },
  { id: 9, name: "Matte Polarized Sunglasses", price: 55.00, category: "Accessories", rating: 4.5, reviews: 276, image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=600&q=80", description: "Classic wayfarer frame design with 100% UV400 protection.", features: ["Anti-glare polarized lenses", "Lightweight matte TR90 frame", "Durable spring hinges", "Hard case included"] },
  { id: 10, name: "Pop-Up Card Wallet", price: 50.00, category: "Accessories", rating: 4.9, reviews: 488, image: "https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=600&q=80", description: "Slim front-pocket aluminum wallet with an instant card-eject mechanism.", features: ["Holds 6-8 cards", "Space-grade aluminum", "Cash strap included", "RFID blocking"] },
  { id: 11, name: "Waxed Canvas Messenger Bag", price: 75.00, category: "Accessories", rating: 4.7, reviews: 312, image: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=600&q=80", description: "Rugged and spacious vintage-style messenger bag for work or travel.", features: ["Water-resistant waxed canvas", "Adjustable shoulder strap", "Padded laptop sleeve", "Brass hardware"] },
  { id: 12, name: "Woven Braided Stretch Belt", price: 28.00, category: "Accessories", rating: 4.6, reviews: 194, image: "https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=600&q=80", description: "Stretchable and comfortable braided belt for an exact fit every time.", features: ["No-hole exact fit", "Premium elastic stretch", "Genuine leather trim", "Matte zinc alloy buckle"] },

  // --- WORKSPACE ---
  { id: 13, name: "MX Master Ergonomic Mouse", price: 99.99, category: "Workspace", rating: 4.9, reviews: 1320, image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=600&q=80", description: "Engineered for advanced creators with a sculpted, ergonomic shape.", features: ["MagSpeed scroll wheel", "Track-on-glass sensor", "USB-C quick charge", "App-specific customizations"] },
  { id: 14, name: "Premium Wool Felt Desk Pad", price: 35.00, category: "Workspace", rating: 4.6, reviews: 245, image: "https://images.unsplash.com/photo-1621252179027-94459d278660?auto=format&fit=crop&w=600&q=80", description: "Add warmth and texture to your workspace while protecting your desk.", features: ["35\" x 17\" large surface", "Anti-slip cork base", "Soft merino wool blend", "Scratch resistant"] },
  { id: 15, name: "Solid Wood Monitor Stand", price: 65.00, category: "Workspace", rating: 4.8, reviews: 192, image: "https://images.unsplash.com/photo-1542282088-fe8426682b8f?auto=format&fit=crop&w=600&q=80", description: "Elevate your screen to eye level and organize your desk accessories.", features: ["Solid walnut wood", "Supports up to 50 lbs", "Keyboard storage underneath", "Eco-friendly finish"] },
  { id: 16, name: "Architect LED Desk Lamp", price: 74.99, category: "Workspace", rating: 4.7, reviews: 304, image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=600&q=80", description: "Wide-spread illumination with auto-dimming and color temperature controls.", features: ["Auto-brightness sensor", "Zero screen glare", "Adjustable swing arm", "Touch controls"] },
  { id: 17, name: "Executive Leather Notebook", price: 28.00, category: "Workspace", rating: 4.9, reviews: 510, image: "https://images.unsplash.com/photo-1531346878377-a541e4ab04ce?auto=format&fit=crop&w=600&q=80", description: "Thick, fountain-pen friendly paper wrapped in a professional leather cover.", features: ["120gsm ivory paper", "Dotted grid layout", "Lay-flat thread binding", "Dual ribbon markers"] },
  { id: 18, name: "Under-Desk Cable Organizer Box", price: 24.99, category: "Workspace", rating: 4.5, reviews: 232, image: "https://images.unsplash.com/photo-1610461888750-10bfc601b874?auto=format&fit=crop&w=600&q=80", description: "Instantly hide messy cords and power strips for a cleaner aesthetic.", features: ["Ventilation slots", "Real bamboo lid", "Fits oversized power strips", "Includes cable ties"] },

  // --- HOME ---
  { id: 19, name: "Artisan Ceramic Pour-Over", price: 42.00, category: "Home", rating: 4.9, reviews: 167, image: "https://images.unsplash.com/photo-1544233726-9f1d2b27be8b?auto=format&fit=crop&w=600&q=80", description: "Hand-crafted pour-over coffee maker designed for the perfect daily extraction.", features: ["High-heat retention clay", "V60 spiral internal ribbing", "Dishwasher & microwave safe", "Wooden base ring"] },
  { id: 20, name: "Double-Walled Steel Tumbler", price: 32.50, category: "Home", rating: 4.8, reviews: 812, image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80", description: "Keep your drinks ice-cold for 24 hours or piping hot for 12 hours.", features: ["Vacuum insulation technology", "18/8 kitchen-grade steel", "Spill-proof sliding lid", "Cup-holder friendly"] },
  { id: 21, name: "Ultrasonic Stone Diffuser", price: 55.99, category: "Home", rating: 4.6, reviews: 218, image: "https://images.unsplash.com/photo-1608528577891-eb055944f2e7?auto=format&fit=crop&w=600&q=80", description: "Matte ceramic essential oil diffuser that doubles as a piece of home decor.", features: ["Continuous or intermittent mist", "Waterless auto shut-off", "Whisper-quiet operation", "Subtle ambient LED glow"] },
  { id: 22, name: "Sandalwood & Fig Soy Candle", price: 28.00, category: "Home", rating: 4.9, reviews: 375, image: "https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=600&q=80", description: "Complex, earthy fragrance hand-poured into a minimalist reusable amber jar.", features: ["100% natural soy wax", "Lead-free double cotton wicks", "60-hour slow burn time", "Paraben & Phthalate-free"] },
  { id: 23, name: "Chunky Hand-Knit Throw Blanket", price: 85.00, category: "Home", rating: 4.9, reviews: 440, image: "https://images.unsplash.com/photo-1583335513577-224a138bb999?auto=format&fit=crop&w=600&q=80", description: "Ultra-soft, weighted-feel cozy blanket perfect for couch lounging.", features: ["100% Premium Cotton tubing", "Hand-knitted construction", "Machine washable on delicate", "Generous 50\" x 60\" size"] },
  { id: 24, name: "Textured Minimalist Plant Pot", price: 22.00, category: "Home", rating: 4.7, reviews: 185, image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=600&q=80", description: "Modern matte ceramic planter designed for optimal indoor plant health.", features: ["7-inch inner diameter", "Matte unglazed finish", "Seamless matching saucer", "Pre-drilled drainage hole"] },

  // --- APPAREL ---
  { id: 25, name: "Heavyweight Boxy Cotton Tee", price: 32.00, category: "Apparel", rating: 4.8, reviews: 550, image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=600&q=80", description: "A premium, structured vintage-wash t-shirt built for everyday durability.", features: ["100% organic heavy cotton", "Garment-dyed & pre-shrunk", "Relaxed boxy fit", "Thick ribbed collar"] },
  { id: 26, name: "French Terry Zip Hoodie", price: 75.00, category: "Apparel", rating: 4.8, reviews: 282, image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=600&q=80", description: "Your new go-to hoodie, featuring a breathable yet warm interior.", features: ["100% Cotton French Terry", "Heavy-duty YKK metal zipper", "Double-lined hood", "Reinforced kangaroo pockets"] },
  { id: 27, name: "Selvedge Denim Jacket", price: 110.00, category: "Apparel", rating: 4.6, reviews: 310, image: "https://images.unsplash.com/photo-1576871337622-98d48d1cf531?auto=format&fit=crop&w=600&q=80", description: "Timeless, raw denim jacket that molds to your body and fades uniquely over time.", features: ["12oz raw selvedge denim", "Shank button closure", "Dual chest & welt pockets", "Adjustable waist tabs"] },
  { id: 28, name: "Merino Wool Fisherman Beanie", price: 28.00, category: "Apparel", rating: 4.7, reviews: 245, image: "https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?auto=format&fit=crop&w=600&q=80", description: "Keep warm in style with this temperature-regulating ribbed beanie.", features: ["100% fine merino wool", "Shallow fisherman fit", "Fold-over cuff", "Naturally odor-resistant"] },
  { id: 29, name: "Ultralight Packable Windbreaker", price: 85.00, category: "Apparel", rating: 4.5, reviews: 192, image: "https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=600&q=80", description: "Water-repellent and incredibly light jacket for unpredictable weather.", features: ["DWR water-repellent finish", "Breathable mesh back panel", "Packs into its own chest pocket", "Elastic bound cuffs"] },
  { id: 30, name: "Performance Cushioned Crew Socks", price: 18.00, category: "Apparel", rating: 4.9, reviews: 820, image: "https://images.unsplash.com/photo-1582966772680-860e372bb558?auto=format&fit=crop&w=600&q=80", description: "Comfortable, moisture-wicking socks sold in a convenient 3-pack.", features: ["Terry-loop padded sole", "Mid-foot arch support compression", "Moisture-wicking yarn blend", "Anti-blister seamless toe"] },

  // --- FITNESS ---
  { id: 31, name: "Pro Alignment Yoga Mat", price: 58.00, category: "Fitness", rating: 4.9, reviews: 390, image: "https://images.unsplash.com/photo-1592432678016-e910b06b384a?auto=format&fit=crop&w=600&q=80", description: "Extremely grippy, wide yoga mat made from sustainable natural tree rubber.", features: ["5mm extra-dense cushioning", "Laser-engraved alignment lines", "Anti-microbial closed-cell surface", "Adjustable carrying strap included"] },
  { id: 32, name: "Non-Slip Fabric Resistance Bands", price: 29.99, category: "Fitness", rating: 4.7, reviews: 643, image: "https://images.unsplash.com/photo-1598289431512-b97b0a150b18?auto=format&fit=crop&w=600&q=80", description: "Set of 3 premium fabric glute bands that will never roll up or snap.", features: ["Thick cotton-latex blend", "3 heavy resistance levels", "Inner grip strips", "Mesh travel bag included"] },
  { id: 33, name: "Deep Tissue Trigger Point Roller", price: 36.00, category: "Fitness", rating: 4.8, reviews: 275, image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=600&q=80", description: "Grid-textured roller perfect for deep tissue massage and fast muscle recovery.", features: ["Multi-density 3D grid surface", "Hollow core firm EVA foam", "Supports up to 500 lbs", "13-inch travel-friendly length"] },
  { id: 34, name: "Quick-Select Adjustable Dumbbells", price: 249.00, category: "Fitness", rating: 4.9, reviews: 912, image: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=600&q=80", description: "Replace an entire rack of weights with these space-saving adjustable dumbbells.", features: ["Dial adjusts from 5 to 52.5 lbs", "Quiet, smooth plate transitions", "Ergonomic knurled grips", "Heavy-duty storage trays included"] },
  { id: 35, name: "Cross-Training Speed Jump Rope", price: 18.00, category: "Fitness", rating: 4.6, reviews: 210, image: "https://images.unsplash.com/photo-1515523110800-9415d13b84a8?auto=format&fit=crop&w=600&q=80", description: "Lightning-fast steel cable jump rope designed for double-unders and HIIT.", features: ["Smooth 360-degree ball bearings", "Easily adjustable cable length", "Textured aluminum handles", "Tangle-free coated steel wire"] },
  { id: 36, name: "Stainless Steel Protein Shaker", price: 19.99, category: "Fitness", rating: 4.7, reviews: 430, image: "https://images.unsplash.com/photo-1576722880053-27a3717df392?auto=format&fit=crop&w=600&q=80", description: "Odor-resistant, leak-proof steel shaker bottle for smooth supplement mixing.", features: ["26oz volume capacity", "Food-grade stainless steel body", "Surgical-grade wire whisk ball", "Secure snap-closure flip cap"] },

  // --- TRAVEL ---
  { id: 37, name: "Hardside Expandable Carry-On", price: 129.00, category: "Travel", rating: 4.8, reviews: 420, image: "https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?auto=format&fit=crop&w=600&q=80", description: "Lightweight polycarbonate luggage built to withstand the rigors of travel.", features: ["TSA-approved combination lock", "360-degree spinner wheels", "Expandable by 2 inches", "Internal compression straps"] },
  { id: 38, name: "Compression Packing Cubes (Set of 4)", price: 34.00, category: "Travel", rating: 4.9, reviews: 815, image: "https://images.unsplash.com/photo-1550974358-3d14ab527f32?auto=format&fit=crop&w=600&q=80", description: "Maximize suitcase space and organize your clothes with these compression cubes.", features: ["Double zipper compression system", "Water-resistant nylon", "Breathable mesh panels", "Includes laundry bag"] },
  { id: 39, name: "Memory Foam Travel Neck Pillow", price: 29.50, category: "Travel", rating: 4.7, reviews: 590, image: "https://images.unsplash.com/photo-1584897275036-7e3e09849221?auto=format&fit=crop&w=600&q=80", description: "Ergonomic neck support designed for long-haul flights and road trips.", features: ["High-density memory foam", "Washable cooling cover", "Adjustable front clasp", "Compresses into travel pouch"] },
  { id: 40, name: "Leather Passport Holder Wallet", price: 38.00, category: "Travel", rating: 4.8, reviews: 210, image: "https://images.unsplash.com/photo-1544465544-1b71aee9dfa3?auto=format&fit=crop&w=600&q=80", description: "Keep your essential travel documents secure and accessible in one place.", features: ["Premium full-grain leather", "RFID-blocking lining", "Holds passport & boarding pass", "4 card slots + pen holder"] },
  { id: 41, name: "Universal Travel Power Adapter", price: 24.99, category: "Travel", rating: 4.6, reviews: 1045, image: "https://images.unsplash.com/photo-1599839619722-39751411ea63?auto=format&fit=crop&w=600&q=80", description: "All-in-one wall charger covering over 150 countries worldwide.", features: ["US/EU/UK/AUS plug compatibility", "3 USB-A & 1 USB-C ports", "Built-in smart safety fuse", "Simultaneous multi-device charging"] },
  { id: 42, name: "Hanging Water-Resistant Toiletry Bag", price: 28.00, category: "Travel", rating: 4.7, reviews: 340, image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80", description: "Spacious organizer that hangs on a towel rack for easy access to toiletries.", features: ["Water-resistant polyester exterior", "Sturdy metal hanging hook", "Clear leak-proof compartments", "Elastic bottle holders"] },

  // --- GROOMING ---
  { id: 43, name: "Premium Men's Grooming Kit", price: 45.00, category: "Grooming", rating: 4.8, reviews: 185, image: "https://images.unsplash.com/photo-1621607512214-68297480165e?auto=format&fit=crop&w=600&q=80", description: "Everything you need for daily maintenance, packaged in a sleek leather roll.", features: ["Stainless steel nail clippers", "Slant-tip tweezers", "Multi-purpose grooming scissors", "Leather storage roll"] },
  { id: 44, name: "Sonic Electric Toothbrush", price: 69.99, category: "Grooming", rating: 4.9, reviews: 750, image: "https://images.unsplash.com/photo-1589139265961-07ee4b7a7c1b?auto=format&fit=crop&w=600&q=80", description: "Advanced sonic technology for a dentist-clean feeling every day.", features: ["40,000 micro-brushes per minute", "4 distinct brushing modes", "30-day battery life", "Includes 2 replacement heads"] },
  { id: 45, name: "Double-Edge Safety Razor Set", price: 34.00, category: "Grooming", rating: 4.7, reviews: 310, image: "https://images.unsplash.com/photo-1585237894364-750f68d30e3b?auto=format&fit=crop&w=600&q=80", description: "Achieve a barbershop-quality shave while reducing plastic waste.", features: ["Weighted chrome-plated handle", "Closed comb design", "Includes 10 platinum blades", "Non-slip knurled grip"] },
  { id: 46, name: "Sandalwood & Argan Beard Oil", price: 18.00, category: "Grooming", rating: 4.8, reviews: 420, image: "https://images.unsplash.com/photo-1623910271167-1db256a73c1d?auto=format&fit=crop&w=600&q=80", description: "Nourishing daily oil that softens coarse hair and eliminates beard itch.", features: ["100% natural carrier oils", "Infused with Jojoba and Argan", "Subtle woodsy sandalwood scent", "Glass bottle with dropper"] },
  { id: 47, name: "Texturizing Sea Salt Hair Spray", price: 16.50, category: "Grooming", rating: 4.5, reviews: 290, image: "https://images.unsplash.com/photo-1588667556947-f4728518e3e4?auto=format&fit=crop&w=600&q=80", description: "Add instant volume, texture, and a light matte hold to your hair.", features: ["Natural kelp extract", "Alcohol and paraben-free", "Light, refreshing coconut scent", "Provides heat protection"] },
  { id: 48, name: "Cordless Ceramic Hair Clipper", price: 54.00, category: "Grooming", rating: 4.6, reviews: 155, image: "https://images.unsplash.com/photo-1599305090598-fe179d501227?auto=format&fit=crop&w=600&q=80", description: "Professional-grade trimmer for precise haircuts and beard styling at home.", features: ["Self-sharpening ceramic blades", "LED battery display", "USB quick charging", "Includes 8 guide combs"] }
];